stages:

  feature_extraction:
    cmd: python -m src.components.feature_extraction
    deps:    
      - src/components/feature_extraction.py
    outs:
      - data/interim/features.csv

  data_preprocessing:
    cmd: python -m src.components.data_preprocessing
    deps:
      - src/components/data_preprocessing.py
      - data/interim/features.csv
    outs:
      - data/preprocessed
      
  model_training:
    cmd: python -m src.pipeline.training_pipeline
    deps:
      - data/preprocessed/train_data.csv
      - data/preprocessed/test_data.csv
      - src/pipeline/training_pipeline.py
      - params.yaml
    outs:
      - models/model.joblib
      - reports/metrics.yaml
