stages:
  feature_extraction:
    cmd: python -m src.components.feature_extraction
    deps:
      - src/components/feature_extraction.py
    outs:
      - data/interim/features.csv

  data_preprocessing:
    cmd: python -m src.components.data_preprocessing
    deps:
      - src/components/data_preprocessing.py
      - data/interim/features.csv
    outs:
      - data/preprocessed
      - artifacts

  model_training:
    cmd: python -m src.pipeline.training_pipeline
    deps:
      - src/pipeline/training_pipeline.py
      - models/model.joblib
      - reports/metrics.yaml
      - params.yaml